server:
  port: 9090
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      
Management:
 endpoints:
  web:
   base-path: /myactuator    
   
  
   exposure:
    include:
     - "*"         
